// Mocks generated by Mockito 5.0.16 from annotations
// in ditonton/test/feature/feature_tv/presentation/provider/tv_show_detail_notfier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/core/util/common/failure.dart' as _i5;
import 'package:ditonton/feature/feature_tv/domain/entities/tv_detail_entities.dart'
    as _i6;
import 'package:ditonton/feature/feature_tv/domain/entities/tv_entities.dart'
    as _i8;
import 'package:ditonton/feature/feature_tv/domain/usecases/get_detail_tv_shows_use_case.dart'
    as _i3;
import 'package:ditonton/feature/feature_tv/domain/usecases/get_recommendation_tv_shows_use_case.dart'
    as _i7;
import 'package:ditonton/feature/feature_tv/domain/usecases/get_watchlist_status_tv_shows_use_case.dart'
    as _i9;
import 'package:ditonton/feature/feature_tv/domain/usecases/remove_watchlist_tv_shows_use_case.dart'
    as _i11;
import 'package:ditonton/feature/feature_tv/domain/usecases/save_watchlist_tv_shows_use_case.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetDetailTvShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailTvShowsUseCase extends _i1.Mock
    implements _i3.GetDetailTvShowsUseCase {
  MockGetDetailTvShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TvDetailEntities>> getDetailTvShows(
          {String? tvId}) =>
      (super.noSuchMethod(
              Invocation.method(#getDetailTvShows, [], {#tvId: tvId}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.TvDetailEntities>>.value(
                      _FakeEither_0<_i5.Failure, _i6.TvDetailEntities>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.TvDetailEntities>>);
}

/// A class which mocks [GetRecommendationTvShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendationTvShowsUseCase extends _i1.Mock
    implements _i7.GetRecommendationTvShowsUseCase {
  MockGetRecommendationTvShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvEntities>>>
      getRecommendationTvShows({String? tvId}) => (super.noSuchMethod(
              Invocation.method(#getRecommendationTvShows, [], {#tvId: tvId}),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i8.TvEntities>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i8.TvEntities>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.TvEntities>>>);
}

/// A class which mocks [GetWatchListStatusTvShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTvShowsUseCase extends _i1.Mock
    implements _i9.GetWatchListStatusTvShowsUseCase {
  MockGetWatchListStatusTvShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [SaveWatchListTvShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchListTvShowsUseCase extends _i1.Mock
    implements _i10.SaveWatchListTvShowsUseCase {
  MockSaveWatchListTvShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlist(
          _i6.TvDetailEntities? tvShow) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvShow]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}

/// A class which mocks [RemoveWatchListTvShowsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchListTvShowsUseCase extends _i1.Mock
    implements _i11.RemoveWatchListTvShowsUseCase {
  MockRemoveWatchListTvShowsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWatchlist(
          _i6.TvDetailEntities? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvShow]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
