// Mocks generated by Mockito 5.0.16 from annotations
// in feature_tv/test/helper/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core/core.dart' as _i4;
import 'package:core/data/models/watch_list_table.dart' as _i7;
import 'package:dartz/dartz.dart' as _i3;
import 'package:feature_tv/data/datasources/tv_local_data_source.dart' as _i13;
import 'package:feature_tv/data/datasources/tv_remote_data_source.dart' as _i8;
import 'package:feature_tv/data/models/tv_detail_model.dart' as _i2;
import 'package:feature_tv/data/models/tv_model.dart' as _i9;
import 'package:feature_tv/domain/entities/tv_detail_entities.dart' as _i12;
import 'package:feature_tv/domain/entities/tv_entities.dart' as _i11;
import 'package:feature_tv/domain/repositories/tv_repositories.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvDetailModel_0 extends _i1.Fake implements _i2.TvDetailModel {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i4.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i6.Database?>.value()) as _i5.Future<_i6.Database?>);
  @override
  _i5.Future<int> insertMovieWatchlist(_i7.WatchListTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeMovieWatchlist(_i7.WatchListTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
  @override
  _i5.Future<int> insertTvShowWatchlist(_i7.WatchListTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#insertTvShowWatchlist, [tvShow]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<int> removeTvShowWatchlist(_i7.WatchListTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeTvShowWatchlist, [tvShow]),
          returnValue: Future<int>.value(0)) as _i5.Future<int>);
  @override
  _i5.Future<Map<String, dynamic>?> getTvShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i5.Future<Map<String, dynamic>?>);
  @override
  _i5.Future<List<Map<String, dynamic>>> getWatchlistTvShows() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvShows, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i8.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.TvModel>> getNowPlayingTvShows() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvShows, []),
              returnValue: Future<List<_i9.TvModel>>.value(<_i9.TvModel>[]))
          as _i5.Future<List<_i9.TvModel>>);
  @override
  _i5.Future<List<_i9.TvModel>> getPopularTvShows() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvShows, []),
              returnValue: Future<List<_i9.TvModel>>.value(<_i9.TvModel>[]))
          as _i5.Future<List<_i9.TvModel>>);
  @override
  _i5.Future<List<_i9.TvModel>> getTopRatedTvShows() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvShows, []),
              returnValue: Future<List<_i9.TvModel>>.value(<_i9.TvModel>[]))
          as _i5.Future<List<_i9.TvModel>>);
  @override
  _i5.Future<_i2.TvDetailModel> getDetailTvShows({String? tvId}) => (super
          .noSuchMethod(Invocation.method(#getDetailTvShows, [], {#tvId: tvId}),
              returnValue:
                  Future<_i2.TvDetailModel>.value(_FakeTvDetailModel_0()))
      as _i5.Future<_i2.TvDetailModel>);
  @override
  _i5.Future<List<_i9.TvModel>> getRecommendationTvShows({String? tvId}) =>
      (super.noSuchMethod(
              Invocation.method(#getRecommendationTvShows, [], {#tvId: tvId}),
              returnValue: Future<List<_i9.TvModel>>.value(<_i9.TvModel>[]))
          as _i5.Future<List<_i9.TvModel>>);
  @override
  _i5.Future<List<_i9.TvModel>> searchTvShows(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvShows, [query]),
              returnValue: Future<List<_i9.TvModel>>.value(<_i9.TvModel>[]))
          as _i5.Future<List<_i9.TvModel>>);
}

/// A class which mocks [TvRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepositories extends _i1.Mock implements _i10.TvRepositories {
  MockTvRepositories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>
      getNowPlayingTvShows() => (super.noSuchMethod(
              Invocation.method(#getNowPlayingTvShows, []),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>
      getPopularTvShows() => (super.noSuchMethod(
              Invocation.method(#getPopularTvShows, []),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>
      getTopRatedTvShows() => (super.noSuchMethod(
              Invocation.method(#getTopRatedTvShows, []),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, _i12.TvDetailEntities>> getDetailTvShows(
          {String? tvId}) =>
      (super.noSuchMethod(
              Invocation.method(#getDetailTvShows, [], {#tvId: tvId}),
              returnValue:
                  Future<_i3.Either<_i4.Failure, _i12.TvDetailEntities>>.value(
                      _FakeEither_1<_i4.Failure, _i12.TvDetailEntities>()))
          as _i5.Future<_i3.Either<_i4.Failure, _i12.TvDetailEntities>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>
      getRecommendationTvShows({String? tvId}) => (super.noSuchMethod(
              Invocation.method(#getRecommendationTvShows, [], {#tvId: tvId}),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, String>> saveWatchlist(
          _i12.TvDetailEntities? tvShow) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvShow]),
              returnValue: Future<_i3.Either<_i4.Failure, String>>.value(
                  _FakeEither_1<_i4.Failure, String>()))
          as _i5.Future<_i3.Either<_i4.Failure, String>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, String>> removeWatchlist(
          _i12.TvDetailEntities? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvShow]),
              returnValue: Future<_i3.Either<_i4.Failure, String>>.value(
                  _FakeEither_1<_i4.Failure, String>()))
          as _i5.Future<_i3.Either<_i4.Failure, String>>);
  @override
  _i5.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>
      getWatchlistTvShows() => (super.noSuchMethod(
              Invocation.method(#getWatchlistTvShows, []),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
  @override
  _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>> searchTvShows(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvShows, [query]),
              returnValue:
                  Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>.value(
                      _FakeEither_1<_i4.Failure, List<_i11.TvEntities>>()))
          as _i5.Future<_i3.Either<_i4.Failure, List<_i11.TvEntities>>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i13.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> insertWatchlist(_i7.WatchListTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tvShow]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<String> removeWatchlist(_i7.WatchListTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvShow]),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i7.WatchListTable?> getTvShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowById, [id]),
              returnValue: Future<_i7.WatchListTable?>.value())
          as _i5.Future<_i7.WatchListTable?>);
  @override
  _i5.Future<List<_i7.WatchListTable>> getWatchlistTvShows() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvShows, []),
          returnValue: Future<List<_i7.WatchListTable>>.value(
              <_i7.WatchListTable>[])) as _i5.Future<List<_i7.WatchListTable>>);
}

/// A class which mocks [ApiHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiHelper extends _i1.Mock implements _i4.ApiHelper {
  MockApiHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> get({String? url}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#url: url}),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
}
